name: Build Docker Image (artifact)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t xvexitong:latest .

      - name: Save Docker image to tar
        run: |
          docker save xvexitong:latest -o xvexitong.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: xvexitong-image
          path: xvexitong.tar
          retention-days: 7
